package golang

import (
	"go/ast"
	"io/fs"
	"log/slog"
	"path/filepath"
	"strings"

	"github.com/sevigo/goframe/schema"
)

type GoPlugin struct {
	logger *slog.Logger
}

func NewGoPlugin(logger *slog.Logger) schema.ParserPlugin {
	return &GoPlugin{
		logger: logger,
	}
}

func (p *GoPlugin) Name() string {
	return "go"
}

func (p *GoPlugin) Extensions() []string {
	return []string{".go"}
}

func (p *GoPlugin) CanHandle(path string, info fs.FileInfo) bool {
	if info != nil && info.IsDir() {
		return false
	}

	ext := filepath.Ext(path)
	if strings.HasSuffix(path, "_test.go") {
		return false
	}
	return ext == ".go"
}

// IsGenerated checks if the Go file matches common generated code patterns
func (p *GoPlugin) IsGenerated(content string, path string) bool {
	// 1. Check extension first (fast)
	if strings.HasSuffix(path, ".pb.go") ||
		strings.HasSuffix(path, "_gen.go") ||
		strings.HasSuffix(path, ".mock.go") {
		return true
	}

	// 2. Check first 10 lines for common generated headers
	lines := strings.SplitN(content, "\n", 10)

	generatedHeaders := []string{
		"code generated",
		"do not edit",
		"automatically generated",
		"generated by protoc",
	}

	for _, line := range lines {
		lowerLine := strings.ToLower(line)
		for _, header := range generatedHeaders {
			if strings.HasPrefix(lowerLine, "//") && strings.Contains(lowerLine, header) {
				return true
			}
		}
	}
	return false
}

// getVisibility determines if a Go identifier is public or private
func (p *GoPlugin) getVisibility(name string) string {
	if ast.IsExported(name) {
		return "public"
	}
	return "private"
}
