package documentloaders_test

import (
	"context"
	"io/fs"
	"log/slog"
	"os"
	"path/filepath"
	"testing"
	"testing/fstest"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/sevigo/goframe/documentloaders"
	"github.com/sevigo/goframe/parsers"
	"github.com/sevigo/goframe/parsers/golang"
	"github.com/sevigo/goframe/parsers/protobuf"
	"github.com/sevigo/goframe/parsers/typescript"
)

func TestGitLoader_GeneratedCodeDetection(t *testing.T) {
	mockFS := fstest.MapFS{
		"src/normal.go":         {Data: []byte("package main\n\nfunc main() {}")},
		"src/generated.pb.go":   {Data: []byte("package src\n// Code generated by protoc-gen-go. DO NOT EDIT.")},
		"src/mocks/mock_foo.go": {Data: []byte("// Code generated by MockGen. DO NOT EDIT.\npackage mocks")},
		"src/manual_ignore.go":  {Data: []byte("// Code generated manually but header present. DO NOT EDIT.\npackage src")},
		"src/some_gen.go":       {Data: []byte("package src\n// Just a suffix match")},
		"src/api.d.ts":          {Data: []byte("export declare type User = { id: string; }")},
		"src/client_gen.ts":     {Data: []byte("// Code generated by openapi-generator. DO NOT EDIT.\nexport class Client {}")},
		"src/other.ts":          {Data: []byte("export const x = 1;")},
		"src/schema.proto":      {Data: []byte("syntax = \"proto3\";\npackage src;")},
		"src/gen.proto":         {Data: []byte("// Code generated by internal-tool. DO NOT EDIT.\nsyntax = \"proto3\";")},
	}

	tempDir := t.TempDir()
	err := fs.WalkDir(mockFS, ".", func(path string, d fs.DirEntry, err error) error {
		require.NoError(t, err)
		targetPath := filepath.Join(tempDir, path)
		if d.IsDir() {
			return os.MkdirAll(targetPath, 0755)
		}
		data, readErr := mockFS.ReadFile(path)
		require.NoError(t, readErr)
		return os.WriteFile(targetPath, data, 0644)
	})
	require.NoError(t, err)

	logger := slog.New(slog.NewTextHandler(os.Stdout, nil))
	registry := parsers.NewRegistry(logger)
	_ = registry.RegisterParser(golang.NewGoPlugin(logger))
	_ = registry.RegisterParser(typescript.NewTypeScriptPlugin(logger))
	_ = registry.RegisterParser(protobuf.NewProtobufParser(logger))
	// No text parser needed for these files, or add if needed

	// Case 1: Detection Disabled (Default)
	loader, err := documentloaders.NewGit(tempDir, registry)
	require.NoError(t, err)
	docs, err := loader.Load(context.Background())
	require.NoError(t, err)
	assert.Len(t, docs, 10, "Should load all files when detection is disabled")

	// Case 2: Detection Enabled
	loader, err = documentloaders.NewGit(tempDir, registry, documentloaders.WithGeneratedCodeDetection(true))
	require.NoError(t, err)
	docs, err = loader.Load(context.Background())
	require.NoError(t, err)

	// Expected:
	// - normal.go: KEPT
	// - generated.pb.go: SKIPPED (suffix)
	// - mocks/mock_foo.go: SKIPPED (header)
	// - manual_ignore.go: SKIPPED (header)
	// - some_gen.go: SKIPPED (suffix)

	// Wait, Check logic in git.go:
	// Suffixes: .pb.go, _gen.go, .mock.go
	// Headers: "code generated", "do not edit", ...

	// "src/generated.pb.go" -> .pb.go -> Skipped
	// "src/mocks/mock_foo.go" -> header match -> Skipped (if suffix doesn't match, mock_foo.go doesn't match default suffix list)
	// "src/manual_ignore.go" -> header match "code generated" -> Skipped
	// "src/some_gen.go" -> _gen.go -> Skipped

	// So only "src/normal.go" should remain?
	// Let's check detection logic:
	// if extension match OR header match -> skipped.

	// Expected to remain:
	// - normal.go
	// - other.ts
	// - schema.proto

	assert.Len(t, docs, 3, "Should load normal.go, other.ts, and schema.proto")
	if len(docs) != 3 {
		for _, doc := range docs {
			if s, ok := doc.Metadata["source"].(string); ok {
				t.Logf("Loaded: %s", filepath.Base(s))
			}
		}
	}
	if len(docs) > 0 {
		var sources []string
		for _, doc := range docs {
			if s, ok := doc.Metadata["source"].(string); ok {
				sources = append(sources, filepath.Base(s))
			}
		}
		assert.Contains(t, sources, "normal.go")
		assert.Contains(t, sources, "other.ts")
		assert.Contains(t, sources, "schema.proto")
	}
}
