package documentloaders_test

import (
	"context"
	"io/fs"
	"log/slog"
	"os"
	"path/filepath"
	"testing"
	"testing/fstest"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/sevigo/goframe/documentloaders"
	"github.com/sevigo/goframe/parsers"
	"github.com/sevigo/goframe/parsers/golang"
)

func TestGitLoader_GeneratedCodeDetection(t *testing.T) {
	mockFS := fstest.MapFS{
		"src/normal.go":         {Data: []byte("package main\n\nfunc main() {}")},
		"src/generated.pb.go":   {Data: []byte("package src\n// Code generated by protoc-gen-go. DO NOT EDIT.")},
		"src/mocks/mock_foo.go": {Data: []byte("// Code generated by MockGen. DO NOT EDIT.\npackage mocks")},
		"src/manual_ignore.go":  {Data: []byte("// Code generated manually but header present. DO NOT EDIT.\npackage src")},
		"src/some_gen.go":       {Data: []byte("package src\n// Just a suffix match")},
	}

	tempDir := t.TempDir()
	err := fs.WalkDir(mockFS, ".", func(path string, d fs.DirEntry, err error) error {
		require.NoError(t, err)
		targetPath := filepath.Join(tempDir, path)
		if d.IsDir() {
			return os.MkdirAll(targetPath, 0755)
		}
		data, readErr := mockFS.ReadFile(path)
		require.NoError(t, readErr)
		return os.WriteFile(targetPath, data, 0644)
	})
	require.NoError(t, err)

	logger := slog.New(slog.NewTextHandler(os.Stdout, nil))
	registry := parsers.NewRegistry(logger)
	err = registry.RegisterParser(golang.NewGoPlugin(logger))
	require.NoError(t, err)
	// No text parser needed for these files, or add if needed

	// Case 1: Detection Disabled (Default)
	loader, err := documentloaders.NewGit(tempDir, registry)
	require.NoError(t, err)
	docs, err := loader.Load(context.Background())
	require.NoError(t, err)
	assert.Len(t, docs, 5, "Should load all files when detection is disabled")

	// Case 2: Detection Enabled
	loader, err = documentloaders.NewGit(tempDir, registry, documentloaders.WithGeneratedCodeDetection(true))
	require.NoError(t, err)
	docs, err = loader.Load(context.Background())
	require.NoError(t, err)

	// Expected:
	// - normal.go: KEPT
	// - generated.pb.go: SKIPPED (suffix)
	// - mocks/mock_foo.go: SKIPPED (header)
	// - manual_ignore.go: SKIPPED (header)
	// - some_gen.go: SKIPPED (suffix)

	// Wait, Check logic in git.go:
	// Suffixes: .pb.go, _gen.go, .mock.go
	// Headers: "code generated", "do not edit", ...

	// "src/generated.pb.go" -> .pb.go -> Skipped
	// "src/mocks/mock_foo.go" -> header match -> Skipped (if suffix doesn't match, mock_foo.go doesn't match default suffix list)
	// "src/manual_ignore.go" -> header match "code generated" -> Skipped
	// "src/some_gen.go" -> _gen.go -> Skipped

	// So only "src/normal.go" should remain?
	// Let's check detection logic:
	// if extension match OR header match -> skipped.

	assert.Len(t, docs, 1, "Should only load normal.go when detection is enabled")
	if len(docs) > 0 {
		assert.Contains(t, docs[0].Metadata["source"], "normal.go")
	}
}
